Models/Wallet.cs
using System.ComponentModel.DataAnnotations;

namespace HOTWallets.Models
{
    public class Wallet
    {
        public int Id
        {
            get; set;
        }
        public string Name
        {
            get; set;
        }
        
        public decimal Balance
        {
            get; set;
        }
        public ICollection<CardWallet> CardWallets
        {
            get; set;
        } 
        //public virtual ICollection<Card> Cards
        //{
        //    get; set;
        //}

        public ICollection<Trans> Transactions
        {
            get; set;
        }
    }
}

Pages/AccountSettings.cshtml.cs
using HOTWallets.DataAccess;
using HOTWallets.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HOTWallets.Pages
{
    [Authorize(Roles = "admin")]
    public class AccountSettingsModel : PageModel
    {
        public Account Account
        {
            get; set;
        } = new Account();

        private IAccountDal _accountDal;
        public AccountSettingsModel(IAccountDal accountDal)
        {
            _accountDal = accountDal;
        }
        public void OnGet(int Id)
        {
            Account = _accountDal.GetAccountById(Id);
        }
    }
}

Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HOTWallets.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId
        {
            get; set;
        }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using System.Security.Claims;
using System.Text.Json;
using HOTWallets.DataAccess;
using HOTWallets.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HOTWallets.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        [BindProperty]
        public Card Card
        {
            get; set;
        } = new Card();
        public List<Wallet> Wallets
        {
            get; set;
        } = new List<Wallet>();

        private ICardDal _cardDal;
        private IWalletDal _walletDal;
        public IndexModel(ILogger<IndexModel> logger, ICardDal cardDal, IWalletDal walletDal)
        {
            _logger = logger;
            _cardDal = cardDal;
            _walletDal = walletDal;
        }

        public IActionResult OnGet()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToPage("Main");
            }
            return Page();
        }

        public IActionResult OnGetSignUp()
        {
            return Partial("_Register");
        }

        public IActionResult OnPostSignIn(string username, string password)
        {

            if (!String.IsNullOrWhiteSpace(username) || !String.IsNullOrWhiteSpace(username))
            {
                if (_cardDal.CardCheck(x=> x.Username == username && x.Password == password, out var card))
                {
                    //HttpContext.Session.Set<MainPageDataModel>("userinfo", dataModel);
                    //MainPageDataModel model = HttpContext.Session.Get<MainPageDataModel>("userinfo");

                    //HttpContext.Response.Cookies.Append("username", Username);

                    var claims = new List<Claim>
                    {
                        new Claim (ClaimTypes.NameIdentifier, card.Id.ToString()),
                        new Claim (ClaimTypes.Name, card.Username),
                        new Claim (ClaimTypes.Role, card.Role)
                    };

                    var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                    HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));

                    return RedirectToPage("Main");
                    //return RedirectToPage("Main", new { data = Card.Id.ToString() });
                }
                ViewData["errormessage"] = "Kullanıcı adı veya şifre hatalı";

                return Page();
            }

            return Page();
        }

        public IActionResult OnGetSignOut()
        {
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            //HttpContext.Session.Clear();
            return RedirectToPage("Index");
        }

        public IActionResult OnPostCreateAcc()
        {
            Wallet wallet = new Wallet { Name = "My Wallet", Balance = 0,  };
            Account account = new Account { Name = Card.Username };
            Card.Account = account;
            Card.CardWallets.Add(new CardWallet { Wallet = wallet });
            _cardDal.Add(Card);
            //_walletDal.Add(new Wallet {Balance = 0, Name = "My Wallet" });
            //var lastWallet =  _walletDal.GetAll().OrderByDescending(x => x.Id).First();
            var lastWallet = _walletDal.LastData();
            return RedirectToPage("Index");

        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HOTWallets.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Stimulus.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HOTWallets.Pages
{
    public class StimulusModel : PageModel
    {
        public void OnGet()
        {

        }

        public IActionResult OnGetAddData()
        {
            return new EmptyResult();
        }
    }
}

Pages/LoginError.cshtml
@model IndexModel

<turbo-frame id="login-frame">
    <form method="post">
        <input type="hidden" name="authenticity_token" autocomplete="off" />
        <div class="flex flex-col justify-center items-center w-96">
            <div class="flex flex-col my-3 w-full">
                <label class="index-label" for="username">Username</label>
                <input asp-for="@Model.Card.Username" required="required" class="rounded-full" type="text" name="username" />
            </div>

            <div class="flex flex-col my-3 w-full">
                <label class="index-label" for="user_password">Password</label>
                <input asp-for="@Model.Card.Password" required="required" class="rounded-full" type="password" name="password" />
            </div>

            <div>
                <div class="flex flex-col justify-center items-center">
                    <button asp-page="/Index" data-turbo="false" asp-page-handler="SignIn" class="my-2 w-full flex justify-center py-2 px-6  text-xl font-medium rounded-full text-white bg-gradient-to-r from-[#CE00D2] to-zinc-700 ">
                        Sign In
                    </button>
                    <a asp-page="/Index" asp-page-handler="SignUp" class="my-2  w-full flex justify-center py-2 px-6 font-bold  text-xl text-transparent text-8xl bg-clip-text bg-gradient-to-r from-[#CE00D2] to-zinc-700 ">
                        Sign Up
                    </a>
                </div>
            </div>
        </div>
    </form>
    <p class="text-red-500">kullanıcı adı veya şifre hartalı</p>
</turbo-frame>

Pages/Stimulus.cshtml
@page
@model HOTWallets.Pages.StimulusModel
@{
}

<div class="flex gap-2 justify-center items-center mt-10" data-controller="stimulus">
    <input type="text" data-stimulus-target="source" />
    <input type="text" data-stimulus-target="source" />
    <button class="p-2 bg-red-500 text-white" data-action="click->stimulus#work">Tıkla</button>
    <p data-stimulus-target="output"></p>
    <p data-stimulus-target="output"></p>
</div>

Pages/_AccountCategories.cshtml
@using System.Text.RegularExpressions
@using HOTWallets.Utilities
@using HtmlAgilityPack
@using Microsoft.AspNetCore.Components
@using Microsoft.AspNetCore.Html
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model Models.Account

<turbo-frame class="flex flex-col justify-center  items-center" id="new_account_category">
    <a asp-page="/Main" asp-page-handler="AddCategory" asp-route-accountId="@Model.Id" class="p-4 text-xl bg-gradient-to-r from-[#CE00D2] to-gray-400 rounded-full text-white font-bold mt-6">New Category</a>

    <div class="flex flex-col items-center" id="edit_account_category">
        <div class="grid grid-cols-7 gap-24 w-full px-32 mt-12" id="edit_categories">
            @foreach (var category in Model.Categories)
            {
                <a asp-page="/Main" asp-page-handler="EditCategory" data-turbo-frame="new_account_category" asp-route-categoryId="@category.Id">
                    <div class="flex flex-col justify-center text-center items-center w-24 h-24" id="categories">
                        @Html.Raw(Utils.GetCategoryIcons()[category.Icon])
                        @*<img class="w-16" src="~/dist/images/categories/@String.Format("{0}.svg", category.Icon)">*@
                        <span class="text-black mt-2 text-lg">@category.Name</span>
                    </div>
                </a>
            }
        </div>
    </div>

</turbo-frame>

Pages/_AccountUsers.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Models.Account

<turbo-frame class="flex flex-col items-center" id="new_account_user">
    <div class="flex gap-4 w-full overflow-x-auto justify-center overflow-visible pb-4">
        <div class="flex items-center space-x-1 ">
            <div class="flex flex-shrink-0 -space-x-2">

                @foreach (var card in Model.Cards)
                {
                    <span class="inline-block relative z-10" data-action="mouseenter->tooltip#open mouseleave->tooltip#close">
                        <div class="tooltip" data-tooltip-target="content" hidden="">
                            @String.Format("{0} {1}", card.FirstName, card.LastName)
                        </div>
                        <span class="inline-flex items-center justify-center ring-1 border-2 ring-[#ffdb4d] h-14 w-14 rounded-full bg-gray-400">
                            <span class="text-sm font-medium leading-none text-white">@String.Format("{0}{1}", card.FirstName[0], card.LastName[0])</span>
                        </span>
                    </span>
                }
            </div>
        </div>

        <a asp-page="/Main" asp-page-handler="AddAccountUser" asp-route-accountId=@Model.Id class="p-4 text-xl bg-gradient-to-r from-[#CE00D2] to-gray-400 rounded-full text-white font-bold">
            <svg class="w-8 h-8" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 251.882 251.882"><path d="M215.037 36.846c-49.129-49.128-129.063-49.128-178.191 0-49.127 49.127-49.127 129.063 0 178.19 24.564 24.564 56.83 36.846 89.096 36.846s64.531-12.282 89.096-36.846c49.126-49.127 49.126-129.063-.001-178.19zM49.574 202.309C7.465 160.2 7.465 91.683 49.574 49.574c21.055-21.054 48.711-31.582 76.367-31.582s55.313 10.527 76.367 31.582c42.109 42.109 42.109 110.626 0 152.735-42.109 42.108-110.625 42.108-152.734 0z"></path><path d="M194.823 116.941h-59.882V57.059c0-4.971-4.029-9-9-9s-9 4.029-9 9v59.882H57.059c-4.971 0-9 4.029-9 9s4.029 9 9 9h59.882v59.882c0 4.971 4.029 9 9 9s9-4.029 9-9v-59.882h59.882c4.971 0 9-4.029 9-9s-4.029-9-9-9z"></path></svg>
        </a>
    </div>
</turbo-frame>

Pages/_AddedTran.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Models.Trans

<turbo-stream action="replace" target="transaction_0">
    <template>
        <turbo-frame id="transaction_0"></turbo-frame>
    </template>
</turbo-stream>
<turbo-stream action="append" target="index_transaction">
    <template>
        <partial name="_WalletTransaction.cshtml" model="@Model"/>
    </template>
</turbo-stream>

@*<turbo-stream action="replace" target="main-frame">
    <template>
        <partial name="_WalletDetail" />
    </template>
</turbo-stream>*@

Pages/_CancelAddTrans.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Models.Trans

<turbo-stream action="replace" target="transaction_@Model.Id">
    <template>
        @if (Model.Id > 0)
        {
            <partial name="_WalletTransaction" model="@Model"></partial>
        }else
        {
            <turbo-frame id="transaction_@Model.Id"></turbo-frame>
        }
        
    </template>
</turbo-stream>

Pages/_EditAccount.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Models.Account

<turbo-frame id="account_@Model.Id" reloadable="">
    <div class="flex flex-col justify-center items-center">
        <form class="flex justify-center flex-col mt-6 w-full" accept-charset="UTF-8" method="post">
            <div class="flex flex-col items-center w-full">
                <div class="font-bold text-transparent text-md bg-clip-text p-2 text-black from-[#CE00D2] to-zinc-700 w-full">
                    @Model.Name
                </div>

                <input type="hidden" asp-for="@Model.Id" />
                <input class="border-2 border-gray-400 rounded-full w-full px-6 text-xl" type="text" value="@Model.Name" name="name" asp-for="@Model.Name" id="account_name">

                <input asp-page="/Main" asp-page-handler="SaveAccount" type="submit" name="commit" value="Save" class="w-auto py-2 px-10 text-md bg-gradient-to-r from-[#CE00D2] to-gray-400 rounded-full text-white font-bold mt-4 cursor-pointer">
            </div>
        </form>

        <a asp-page="/Main" asp-page-handler="CancelAccount" class="mt-2 text-fuchsia-600" asp-route-accountId="@Model.Id" asp-route-name="@Model.Name">Cancel</a>
    </div>

</turbo-frame>

Pages/_HeaderAccountName.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Models.Card

<turbo-frame id="header_account_@Model.AccountId">
    <a href="#">@Model.Account.Name</a>
</turbo-frame>

Pages/_NewWallet.cshtml
@using System.Security.Claims
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    var cardId = Convert.ToInt32(User.FindFirstValue(ClaimTypes.NameIdentifier));
}

@model HOTWallets.Pages.MainModel

<turbo-frame id="newwallet_@cardId">
    <form method="post">
        <div class="flex flex-col w-96 justify-center items-center">
            <input class="border-2 border-gray-400 mb-4 rounded-md" placeholder="Name" asp-for=@Model.Wallet.Name type="text">
            <div class="flex flex-col border-2 border-gray-200 w-[23rem] p-2 rounded-md mb-4">
                <label for="wallet_users">Users</label>
                <div class="flex flex-wrap flex-row items-center gap-2">
                    @foreach (var card in Model.Account.Cards)
                    {
                        <div>
                            <input type="checkbox" disabled=@(card.Id == cardId) name="userIds" checked=@(card.Id == cardId) value=@card.Id />
                            @card.Username
                        </div>
                    }
                </div>
            </div>
            <div class="flex flex-row gap-2">
                <input asp-page="/Main" asp-page-handler="CreateWallet" asp-route-userid=@Model.Card.Id type="submit" name="commit" value="Save" class="w-auto py-2 px-10 text-md bg-gradient-to-r from-[#CE00D2] to-gray-400 rounded-full text-white font-bold mt-4 cursor-pointer">
            </div>
        </div>
    </form>
</turbo-frame>

Pages/_UpdateAccount.cshtml
@using HOTWallets.DataAccess
@using System.Security.Claims
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model Models.Account

@{
    CardDal cardDal = new CardDal();
    var card = cardDal.GetById(Convert.ToInt32(User.FindFirstValue(ClaimTypes.NameIdentifier)));
}

<turbo-stream action="replace" target="account_@Model.Id">
    <template>
        <partial name="_AccountInfo.cshtml" model=@Model/>
    </template>
</turbo-stream>

<turbo-stream action="replace" target="header_account_@Model.Id">
    <template>
        <partial name="_HeaderAccountName.cshtml" model="@card"/>
    </template>
</turbo-stream>

Pages/_WalletTransaction.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Models.Trans

<turbo-frame id="transaction_@Model.Id">
    <div class="flex flex-row justify-between items-start mt-5">
        <div>
            <a asp-page="/Main" asp-page-handler="DeleteTransaction" data-turbo-frame="main-frame" asp-route-id="@Model.Id" asp-route-walletid="@Model.WalletId" class="rounded-full py-2 px-4 bg-gray-100 inline-block font-medium">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0"></path>
                </svg>
            </a>
        </div>
        <div class="text-4xl font-bold mt-4">
            @(Model.Type == "expense" ? String.Format("-₺{0}", Model.Price) : String.Format("+₺{0}", Model.Price))
        </div>

        <div>
            <a asp-page="/Main" asp-page-handler="AddTrans" asp-route-cardid="@Model.CardId" asp-route-transid="@Model.Id" asp-route-walletid="@Model.WalletId" class="rounded-full py-2 px-4 bg-gray-100 inline-block font-medium">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10"></path>
                </svg>
            </a>
        </div>
    </div>

    <div class="flex flex-row justify-between items-end">
        <div class="capitalize">
            @Model.Category.Name
        </div>

        <div class="capitalize">
            @Model.Name
        </div>

        <div>
            @String.Format("{0}{1}",Model.Card.FirstName[0], Model.Card.LastName[0])
        </div>
    </div>

    <hr class="w-full border-2 rounded-full">
</turbo-frame>

Pages/_WalletsForNavbar.cshtml
@using HOTWallets.Models
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model List<Wallet>

<turbo-frame id="my_wallets">

    
        @foreach (var wallet in Model)
        {
        @*<div class="border border-gray-400 flex flex-col justify-center items-center p-2 hover:bg-gray-100/75 hover:border-2 group">*@
        <a asp-page="/Main" asp-page-handler="GetWallet" asp-route-id="@wallet.Id" data-turbo-frame="_top" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" >
                @*<div class="border-2 border-gray-400 w-72 h-72 rounded-[64px] flex flex-col justify-center items-center p-8 hover:bg-gray-100/75 hover:border-4 group">*@
                    <p class="text-sm text-gray-800 text-center group-hover:text-black mb-1">@wallet.Name</p>
                @*</div>*@
            </a>
        @*</div>*@
        }
    
</turbo-frame>

Pages/_WelcomeInfo.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Models.Card

<turbo-frame id="welcome-info">
    <section class="flex justify-center items-center flex-col mt-16">
        <p class="text-black font-bold text-5xl">Welcome</p>
        <p class="text-black font-bold text-3xl mt-3 mb-10">@Model.FirstName @Model.LastName</p>
        <hr class="w-full">
    </section>
</turbo-frame>